require 'generate_list.rb'

puts "These are the students in Makers Academy"
40.times { print '-'}
puts 

puts 'Abdul Hassan'
puts 'Alan Bridger'
puts 'alex blease'
puts 'Alexander Levin'
puts 'Ana Nogal'
puts 'Andrew Harrison'
puts 'Andrew Hercules'
puts 'Andrew Snead'
puts 'Anna Jerofejeva'
puts 'Attila Mirk'
puts 'Ayo Obembe'
puts 'Ben Hutchinson'
puts 'Bernard Mordan'
puts 'Camilla van Klinken'
puts 'chris handley'
puts 'Christopher Batts'
puts 'Clare Trembath'
puts 'Claudia B'
puts 'Colin Smif'
puts 'Contra Mundi'
puts 'Craig Horsborough'
puts 'Dale Stevens'
#puts 'Dan Le Dosquet-Bergquist'
puts 'Daniel Cutler'
puts 'Daniel Le Dosquet - Bergquist'
puts 'Denise Yu'
puts 'Edward Byne'
puts 'Elena Garrone'
puts 'Ella Schofield'
puts 'Enrique Comba Riepenhausen'
#puts 'Evgeny Shadchnev'
puts 'Fad Fad'
puts 'Giorgia Amici'
puts 'Hadi Chalabi'
puts 'Izzy Markwick'
puts 'James Carter'
puts 'JANA SANCHEZ'
puts 'Jay Dalu-Chandu'
puts 'John Kiely'
puts 'Johnny Lakin'
#puts 'Jordan Maker'
puts 'Karin Nielsen'
puts 'Margherita Serino'
puts 'Ming Chan'
puts 'Mishal I'
puts 'Nick Dyer'
puts 'Nicole Pellicena'
puts 'Nikesh Ashar'
#puts 'Owner'
puts 'Pavel Redics'
puts 'Rachel Nolan'
puts 'Rich Lake'
puts 'Sam Joseph'
puts 'Sandrine Zhang-Ferron'
puts 'Sean Stevens'
puts 'Shan Hasan'
puts 'Simon Lange'
puts 'Stephen Giles'
puts 'Tim Scully'
puts 'Victoria Stepanovna'
puts 'Yvette Cook'
puts 'Zeeshan Rasool'

puts 'Overall we have 59 great students'